name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:24

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint .

  format:
    runs-on: ubuntu-latest
    container:
      image: node:24

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run format .

  checks:
    uses: ./.github/workflows/checks.yaml
